### ISSUE TITLE
Sandbox/live switch seems borked

### ISSUE THREAD

**Issue by Ubiquitous-X** [rogierkn/IPN#4]
At line 65 in `ipn.php` the sandbox/live switch wont actually switch the modes. Changing it at line 82 instead is currently a work-around to get it working.

**Comment by rogierkn** [comment]
Using 
```php
<?php
$ipn = new \PayPal\IPN(null, TRUE);
```
Should set the sandbox to true. By default it is off. If you don't pass a boolean nothing will happen.

**Comment by Ubiquitous-X** [comment]
Oh of course. Solved everything! Thanks a lot for insanely fast reply!

2015-07-19 14:16 GMT+02:00 Rogier Knoester <notifications@github.com>:

**Comment by rogierkn** [comment]
No problem!
On Jul 19, 2015 14:19, Ubiquitous-X <notifications@github.com> wrote:Oh of course. Solved everything! Thanks a lot for insanely fast reply!

2015-07-19 14:16 GMT+02:00 Rogier Knoester <notifications@github.com>:
